### ISSUE TITLE
include multiple author names and author photos on exhibits display page and exhibit pages?

### ISSUE THREAD

**Issue by phigg** [WGBH-MLA/ov-frontend#48]
Is it possible to list multiple authors and show multiple author photos on exhibit pages and the exhibits display page?

I'd be fine with creating a split-screen-style photo if only one image can be used. [New Critical Television](https://openvault.wgbh.org/exhibits/new_critical_television/authors#tabs) and [The Edwin G. Boring and Hanns Sachs Collection](https://openvault.wgbh.org/exhibits/boring_and_sachs/authors#tabs) are examples of exhibits with multiple authors.

**Comment by ekemeyer** [comment]
Decision made on June 28th mtg:

- [ ] Use Ellipses for multiple authors on exhibits display
- [ ] Only have one bubble/author on exhibits display
- [ ] On individual exhibit pages, have all authors listed and all bubbles

**Comment by foglabs** [comment]
@phigg now that we're including author bios on ex/coll show pages, are we showing a bio for each author? multiple bios could be a little confusing - maybe click on the author bubble/name to reveal the corresponding author bio?

**Comment by phigg** [comment]
@foglabs yes, we should show a bio for each author. I'm okay with multiple author bios. scroll down to bottom of [The Edwin G. Boring and Hanns Sachs Collection](https://openvault.wgbh.org/exhibits/boring_and_sachs/authors#tabs) on current OV to see how it looks
