### ISSUE TITLE
Rotating image not appearing

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/ov-frontend#54]
### Description

On demo (https://ov.wgbh-mla.org/), the image after Julia Child does not appear and the entire area shifts up 

### Reproduction steps

Go to https://ov.wgbh-mla.org/, wait for the 10th image (or click directly on that 10th dot)
Entire section of the page shifts up and crops the image
Everything goes back to normal on the 11th slide.

### Expected behavior

The slideshow should not be disrupted, 10th image should appear as all the others do.

### Screenshots

![Screenshot 2024-06-28 at 11 34 40 AM](https://github.com/WGBH-MLA/ov-frontend/assets/7071688/c5c95d31-6d78-4968-bbd9-5f156c27fefa)

### Browsers

Chrome

**Comment by foglabs** [comment]
great catch - there was no default hero image for the carousel when the exhibit was missing its hero image, so adding that now.

**Comment by mrharpo** [comment]
Fixed with 6558aaa
