### ISSUE TITLE
Arrows instead of text pointer

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/ov-frontend#58]
### Because

Instead of text pointer, it would be better to have an arrow when hovering over anchors on Special Collections and Exhibits.

### Done when

There's an arrow instead of a text pointer

### Additional context
Chrome 126.0.6478.127

**Comment by foglabs** [comment]
@ekemeyer what browser was this on? I know I saw it happen, but tried in firefox and chrome and couldn't reproduce it.

**Comment by ekemeyer** [comment]
Added browser and version in ticket
